title: "Emmitt Paige - Technical Writer"
description: "Cybersecurity & API Documentation Specialist"
baseurl: ""
url: "https://epaige8594.github.io"

# Use tech layout as default
defaults:
  - scope:
      path: ""
    values:
      layout: "tech"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

show_downloads: false
