title: "Emmitt Paige - Technical Writer"
description: "Cybersecurity & API Documentation Specialist"
baseurl: ""
url: "https://epaige8594.github.io"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

markdown: kramdown
permalink: pretty
