title: "Emmitt Paige - Technical Writer"
description: "Cybersecurity & API Documentation Specialist | Top Secret Cleared"
baseurl: ""
url: "https://epaige8594.github.io"
theme: jekyll-theme-cayman

# Custom CSS
sass:
  sass_dir: assets/css

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

show_downloads: false

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: LinkedIn
    url: https://www.linkedin.com/in/emmitt-paige
  - title: Contact
    url: mailto:e.t.paige@gmail.com
