title: "Emmitt Paige - Technical Writer"
description: "Cybersecurity & API Documentation Specialist"
baseurl: ""
url: "https://epaige8594.github.io"
theme: jekyll-theme-minimal

# Explicitly enable Jekyll
markdown: kramdown
highlighter: rouge
permalink: pretty

# Build settings
safe: true
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
